### ISSUE TITLE
Limiting factor

### ISSUE THREAD

**Issue by adelevie** [thomasdondorf/phantomjs-pool#2]
Hi. This is a really neat library and might help me solve a problem at [work](https://18f.gsa.gov). We're trying to figure out efficient ways to run `pa11y` scans across about 1,300 domain names. So far, I've been using AWS Lambda, and I'm reliably getting a concurrency of about 25. But I'm interested in increasing that. Say I could get almost any size EC2 instance ... what kind of RAM or CPU should I be looking for for max consistency?

**Comment by thomasdondorf** [comment]
A concurrency of 25 is already pretty nice. Some findings I did during the use and creation of the library:
- Each worker needs between 50 and 400 MB. It heavily depends on the type of website you are crawling (simple html documents vs. websites that embed other resources, ads, ...). The memory usage per worker will also go up (due to [memory leaks](https://github.com/ariya/phantomjs/issues/11390)), but the library takes care of that.
- A worker that constantly accesses websites needs a throughput of about 2 MBit/s.
- I was able to run about 4 workers per CPU core (on an Intel i7, don't remember details).

But the best thing you can do is just fire up 25 workers and use tools like `nload` and `htop` to find out your limit. `nload` will show you your network usage and `htop` is nice for checking the memory and CPU usage.

Would be cool if you could report your results :)

I close the issue as there is no real benefit for the repository.

**Comment by leeDav** [comment]
Here's some findings from my experiences using this (amazing) tool. I'm quickly testing an idea so hence the slightly sloppy setup.

I had one `t2.2xlarge` EC2 (8 vCPUs and 32GB RAM). On this I was using the PHP dev server (`php -S localhost:8080`) running a single HTML page with a canvas on that would render an image; average render time was around five seconds though sometimes it can be much quicker.

I upped the worker count to 300 overnight and, nine hours later, it generated almost 27,500 screenshots. Average CPU load was around 25%, though it initially hit 95%.

On a whim, I upped the worker count to 3,000 where it processed one, maybe two batches and then displayed the below error. Decreasing to 2,000 workers also produced the error. I'm now running on 1,000 workers and it has just crashed, with the same error; in fact it also crashed the instance and I had to reboot it.

It seems like it's a problem with PhantomJS itself rather than this pool tool.

Between attempts I also killed all PhantomJS processes with `pkill phantomjs` as they were still in the background.

Anyway, I saw this post and thought I'd report with my (unscientific) findings. I'll likely post again as I need more images and I'll try with a meatier EC2.

```
#355 STDERR >> 1   0x1b67967 /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0x1b67967]
#355 STDERR >> 2   0x1889669 /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0x1889669]
#355 STDERR >> 3   0x188ac47 /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0x188ac47]
#355 STDERR >> 4   0x1ac48ae /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0x1ac48ae]
#355 STDERR >> 5   0x1ac7953 /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0x1ac7953]
#355 STDERR >> 6   0x1791a88 /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0x1791a88]
#355 STDERR >> 7   0xb8e930 /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0xb8e930]
#355 STDERR >> 8   0xb8ccf3 /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0xb8ccf3]
#355 STDERR >> 9   0xb8d04b /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0xb8d04b]
#355 STDERR >> 10  0xb8d318 /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0xb8d318]
#355 STDERR >> 11  0xb95747 /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0xb95747]
#355 STDERR >> 12  0x1baadd1 /home/ubuntu/project/node_modules/phantomjs/lib/phantom/bin/phantomjs() [0x1baadd1]
#355 STDERR >> 13  0x7f59cc23c6ba /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f59cc23c6ba]
#355 STDERR >> 14  0x7f59cb6d182d /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f59cb6d182d]
#355 STDERR >> PhantomJS has crashed. Please read the bug reporting guide at
#355 STDERR >> <http://phantomjs.org/bug-reporting.html> and file a bug report.


# here it carries on trying to process them, ultimately failing

/home/ubuntu/project/node_modules/phantomjs-pool/lib/master/WorkerControl.js:67
    this.proc.stdout.on('data', function (rawData) {
                    ^

TypeError: Cannot read property 'on' of undefined
    at Worker.createProcess (/home/ubuntu/project/node_modules/phantomjs-pool/lib/master/WorkerControl.js:67:21)
    at new Worker (/home/ubuntu/project/node_modules/phantomjs-pool/lib/master/WorkerControl.js:32:10)
    at Function.Worker.create (/home/ubuntu/project/node_modules/phantomjs-pool/lib/master/WorkerControl.js:250:12)
    at Pool.addWorker (/home/ubuntu/project/node_modules/phantomjs-pool/lib/master/Pool.js:62:30)
    at Pool.spawnWorkers (/home/ubuntu/project/node_modules/phantomjs-pool/lib/master/Pool.js:50:14)
    at null._onTimeout (/home/ubuntu/project/node_modules/phantomjs-pool/lib/master/Pool.js:52:18)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by thomasdondorf** [comment]
Thank you very much for sharing this interesting data.

So, you let 300 workers run for 9 hours and they produced 27,500 screenshots. That are 0.85 screenshots per second. That means 0.0028 screenshots per second per worker or 353.5 seconds per crawling, which is actually a very low value. You could probably gotten the same number of "screenshots per seconds" with just a few workers (if your website takes roughly 5 seconds to load).

I'm not sure what the constraint here is, though.
- CPU => Maybe. For a complex page, 300 workers for 8 CPU cores seems to be way too much, but I don't know how complex the rendering of the page was. If your average CPU load was 25%, this was probably not the problem.
- Memory => 32GB should be okay, but have you checked the memory usage? As soon as memory swapping happens, everything becomes very very slow.
- Network/Throughput => Not a problem, as the website was accessed from the localhost, right?

All in all, the 27,500 screenshots / 0.0028 crawls per second per worker is a very low value. I'm pretty sure you could improve that value by using less workers. Maybe, the constraint is one of the listed ones.


Regarding the error: Efficiently using 3000 workers (or even 1000) should be really hard (if not impossible). If you take my numbers from about you would need a throughput of roughly 6 GBit/s, between 150GB and 1TB (!) of memory and lots of processing power. You also need to think about other side effects like your TCP/IP stack for example, because if your average page has 10 resources embedded into the page, that means your VM will make 30,000 simultaneous requests. Not sure, if the "average TCP/IP stack" can handle that. So, at that scale I would expect errors to happen, but I don't think this library nor PhantomJS are to blame for that...
